services:
  ishtech-springboot-jwtauth-web-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER_PORT: ${SERVER_PORT_REMOTE:-${SERVER_PORT:-8080}}
        APP_VERSION: ${APP_VERSION}
    image: muneer2ishtech/ishtech-springboot-jwtauth-web:${APP_VERSION:+$APP_VERSION}
    container_name: ishtech_springboot_jwtauth_web_app
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ishtech-springboot-jwtauth-web-postgres:5432/ishtech_dev_db
    ports:
      - "${SERVER_PORT_LOCAL:-${SERVER_PORT:-8080}}:${SERVER_PORT_REMOTE:-${SERVER_PORT:-8080}}"
    depends_on:
      ishtech-springboot-jwtauth-web-postgres:
        condition: service_healthy
    networks:
      - ishtech-springboot-jwtauth-web-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT_LOCAL:-${SERVER_PORT:-8080}}/actuator/health"]
      start_period: 60s

  ishtech-springboot-jwtauth-web-postgres:
    image: postgres:18
    container_name: ishtech_springboot_jwtauth_web_postgres
    environment:
      - POSTGRES_DB=ishtech_dev_db
      - POSTGRES_USER=ishtech_dev_user
      - POSTGRES_PASSWORD=ishtech_dev_pass
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ishtech_springboot_jwtauth_web_postgres_data:/var/lib/postgresql/18/data
      - ./ishtech-springboot-jwtauth-web/src/test/resources/db/postgres/init_db.sql:/docker-entrypoint-initdb.d/jwtauth_dev_init_db.sql
    networks:
      - ishtech-springboot-jwtauth-web-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      start_period: 45s

volumes:
  ishtech_springboot_jwtauth_web_postgres_data:

networks:
  ishtech-springboot-jwtauth-web-network:
    driver: bridge
